name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: 

permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apollo-rust-windows
          path: target/x86_64-pc-windows-msvc/release/*.exe

  release:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: apollo-rust-windows
          path: ./dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
