name: Release

on:
  push:
    tags:
      - "v*.*.*" # triggers on version tags like v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Build release binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apollo-rust-windows-x86_64
          path: target/x86_64-pc-windows-msvc/release/apollo-rust.exe

  release:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: apollo-rust-windows-x86_64
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/apollo-rust.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
